nginx-0.0.3-2004-04-12-20:38:09 import

diff --git a/auto/lib/zlib/make b/auto/lib/zlib/make
--- a/auto/lib/zlib/make
+++ b/auto/lib/zlib/make
@@ -76,6 +76,14 @@ case $PLATFORM in
 
                 done=YES
             ;;
+
+            *)
+                echo "$0: error: invalid --with-zlib=asm=$ZLIB_ASM option."
+                echo "The valid values are \"pentium\" and \"pentiumpro\" only".
+                echo
+
+                exit 1;
+            ;;
         esac
     ;;
 
