nginx-0.0.2-2004-02-09-23:47:18 import

diff --git a/auto/summary b/auto/summary
--- a/auto/summary
+++ b/auto/summary
@@ -24,3 +24,27 @@ case $ZLIB in
 esac
 
 echo
+
+
+if [ $HTTP_REWRITE = YES ]; then
+    if [ $PCRE = NONE -o $PCRE = NO ]; then
+        echo "$0: error: HTTP rewrite module requires PCRE library."
+        echo $ngx_n "You can disable the module by using" $ngx_c
+        echo "--without-http_rewrite_module option"
+        echo "or you have to enable PCRE support"
+        echo
+        exit 1
+    fi
+fi
+
+
+if [ $HTTP_GZIP = YES ]; then
+    if [ $ZLIB = NONE -o $ZLIB = NO ]; then
+        echo "$0: error: HTTP gzip module requires zlib library."
+        echo $ngx_n "You can disable the module by using" $ngx_c
+        echo "--without-http_gzip_module option"
+        echo "or you have to enable zlib support"
+        echo
+        exit 1
+    fi
+fi
