nginx-0.0.7-2004-07-05-10:55:54 import

diff --git a/auto/os/freebsd b/auto/os/freebsd
--- a/auto/os/freebsd
+++ b/auto/os/freebsd
@@ -54,8 +54,26 @@ if [ \( $version -lt 500000 -a $version -ge 430000 \) \
      -o $version -ge 500018 ]
 then
     echo " + using kqueue's NOTE_LOWAT"
-
     have=HAVE_LOWAT_EVENT . auto/have
+fi
+
+
+if [ $USE_THREADS = "rfork" ]; then
+
+    echo " + using rfork()"
+
+    # kqueue's EVFILT_SIGNAL is safe
+
+    if [ $version -gt 460101 ]; then
+        echo " + kqueue's EVFILT_SIGNAL is safe"
+        have=HAVE_SAFE_EVFILT_SIGNAL . auto/have
+    else
+        echo "$0: error: the kqueue's EVFILT_SIGNAL is unsafe on this"
+        echo "FreeBSD version, so --with-threads=rfork could not be used"
+        echo
+
+        exit 1
+    fi
 fi
 
 
